In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
import psutil 
import gc

Duplicate key in file 'C:\\Users\\User\\.matplotlib\\matplotlibrc' line #250.

In [2]:
# cd C:/Users/minih/python_prac1/m5/git-repository/kaggle-m5-accuracy-library/library/

In [3]:
# reduce用
import patair

In [4]:
# STORE = 'TX_1'
# STORE = 'TX_2'
# STORE = 'TX_3'
# STORE = 'CA_1'
# STORE = 'CA_2'
STORE = 'CA_3'
# STORE = 'CA_4'
# STORE = 'WI_1'
# STORE = 'WI_2'
# STORE = 'WI_3'

In [5]:
datas = pd.read_csv(f"add_Clean_Analysis_{STORE}.csv").pipe(patair.reduce_mem_usage)
# dept_id,cat_id の情報を得るために、sales_train_validation.csvを読み込み
#  →マージして情報の取り込み
sales_train_validation = pd.read_csv('input/sales_train_validation.csv')
sales_train_validation = sales_train_validation.loc[:,['item_id','dept_id','cat_id']]
sales_train_validation

Mem. usage decreased to 119.65 Mb (50.0% reduction)

             item_id    dept_id   cat_id
0      HOBBIES_1_001  HOBBIES_1  HOBBIES
1      HOBBIES_1_002  HOBBIES_1  HOBBIES
2      HOBBIES_1_003  HOBBIES_1  HOBBIES
3      HOBBIES_1_004  HOBBIES_1  HOBBIES
4      HOBBIES_1_005  HOBBIES_1  HOBBIES
...              ...        ...      ...
30485    FOODS_3_823    FOODS_3    FOODS
30486    FOODS_3_824    FOODS_3    FOODS
30487    FOODS_3_825    FOODS_3    FOODS
30488    FOODS_3_826    FOODS_3    FOODS
30489    FOODS_3_827    FOODS_3    FOODS

[30490 rows x 3 columns]

In [6]:
datas=datas.merge(sales_train_validation,on='item_id')
datas = datas.iloc[:,1:]
datas

,item_id,week,wday,variable,value,prev_1year,year,date,dept_id,cat_id
0,HOBBIES_1_001,1,1,value_13,NaN,NaN,2013,2013-01-26,HOBBIES_1,HOBBIES
1,HOBBIES_1_001,1,1,value_13,NaN,NaN,2013,2013-01-26,HOBBIES_1,HOBBIES
2,HOBBIES_1_001,1,1,value_13,NaN,NaN,2013,2013-01-26,HOBBIES_1,HOBBIES
3,HOBBIES_1_001,1,1,value_13,NaN,NaN,2013,2013-01-26,HOBBIES_1,HOBBIES
4,HOBBIES_1_001,1,1,value_13,NaN,NaN,2013,2013-01-26,HOBBIES_1,HOBBIES
...,...,...,...,...,...,...,...,...,...,...
34850065,FOODS_3_827,17,2,value_16,NaN,0.0,2016,2016-05-22,FOODS_3,FOODS
34850066,FOODS_3_827,17,2,value_16,NaN,0.0,2016,2016-05-22,FOODS_3,FOODS
34850067,FOODS_3_827,17,2,value_16,NaN,0.0,2016,2016-05-22,FOODS_3,FOODS
34850068,FOODS_3_827,17,2,value_16,NaN,0.0,2016,2016-05-22,FOODS_3,FOODS
34850069,FOODS_3_827,17,2,value_16,NaN,0.0,2016,2016-05-22,FOODS_3,FOODS

In [7]:
def encode_categorical(df, cols):
    
    for col in cols:
        # Leave NaN as it is.
        le = LabelEncoder()
        #not_null = df[col][df[col].notnull()]
        df[col] = df[col].fillna('nan')
        df[col] = pd.Series(le.fit_transform(df[col]), index=df.index)

    return df

In [8]:
datas = encode_categorical(
   datas, ["item_id",'dept_id','cat_id']
).pipe(patair.reduce_mem_usage)
gc.collect()

Mem. usage decreased to 1196.48 Mb (18.2% reduction)

47

In [9]:
datas.sort_values(["item_id", "variable", "week", "wday"], inplace=True)

datas["variable"] = datas["variable"].apply(lambda x: x[-2:])
datas["variable"] = datas["variable"].astype(np.int8)

# datas.drop("Unnamed: 0", axis=1, inplace=True)
datas = datas[datas["variable"] >= 13]
#順序の整った一意なキーを取得
product = pd.read_pickle(f"product/product_{STORE}.pickle")

In [10]:
datas

,item_id,week,wday,variable,value,prev_1year,year,date,dept_id,cat_id
18425160,0,1,1,13,0.0,NaN,2013,2013-01-26,0,0
18425161,0,1,1,13,0.0,NaN,2013,2013-01-26,0,0
18425162,0,1,1,13,0.0,NaN,2013,2013-01-26,0,0
18425163,0,1,1,13,0.0,NaN,2013,2013-01-26,0,0
18425164,0,1,1,13,0.0,NaN,2013,2013-01-26,0,0
...,...,...,...,...,...,...,...,...,...,...
18425155,3048,17,2,16,NaN,0.0,2016,2016-05-22,6,2
18425156,3048,17,2,16,NaN,0.0,2016,2016-05-22,6,2
18425157,3048,17,2,16,NaN,0.0,2016,2016-05-22,6,2
18425158,3048,17,2,16,NaN,0.0,2016,2016-05-22,6,2
18425159,3048,17,2,16,NaN,0.0,2016,2016-05-22,6,2

In [11]:
#一意なキーをnumpy配列で取得
columns = np.array(product["item_id"])

In [12]:
# columns

In [13]:
#各アイテムIDについて、0が15日以上続く区間で昨年の売り上げ(prev365)を射影
for l, item in enumerate(columns):
    buff = datas[datas["item_id"] == item]
    buff.reset_index(inplace=True)
    array = np.array(buff["value"])
    j = 0
    range_list = []
    for i in range(len(array)):
        if array[i] == 0:
            j += 1
        else:
            if j >= 15:
                range_list.extend(np.arange(i-j,i,1))
            j = 0
    if j >= 15:
        range_list.extend(np.arange(i-j+1,i+1,1))
    change_array = np.array(buff.loc[range_list]["index"])
    datas.loc[change_array,"value"] = datas.loc[change_array,"prev_1year"]
    if l % 300 == 0:
        print(f"{l}/3049")

0/3049
300/3049
600/3049
900/3049
1200/3049
1500/3049
1800/3049
2100/3049
2400/3049
2700/3049
3000/3049

In [14]:
datas.to_pickle(f"{STORE}_interpolate.pickle")

In [15]:
!pip install pushbullet.py
from pushbullet import Pushbullet
pb = Pushbullet('o.JGDSmoJrTpAmJqn7rZ16geamzJK9louG')
push = pb.push_note(f"{STORE}完了", "★")

Requirement already satisfied: pushbullet.py in c:\users\user\anaconda3\lib\site-packages (0.11.0)
Requirement already satisfied: python-magic in c:\users\user\anaconda3\lib\site-packages (from pushbullet.py) (0.4.18)
Requirement already satisfied: websocket-client in c:\users\user\anaconda3\lib\site-packages (from pushbullet.py) (0.57.0)
Requirement already satisfied: requests>=1.0.0 in c:\users\user\anaconda3\lib\site-packages (from pushbullet.py) (2.23.0)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from websocket-client->pushbullet.py) (1.12.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests>=1.0.0->pushbullet.py) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests>=1.0.0->pushbullet.py) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests>=1.0.0->pushbullet.py) (2019.9.11)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\user\anaconda3\lib\site-packages (from requests>=1.0.0->pushbullet.py) (3.0.4)

ConnectionError: HTTPSConnectionPool(host='api.pushbullet.com', port=443): Max retries exceeded with url: /v2/devices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119801D0B88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))